<? require_once(FILEROOT.'/header.php'); ?>
		<h1>Community Guidelines</h1>
		<p>Welcome to Gamers' Plane. By accessing or using our site or our Discord, you agree to abide by the following terms. These rules are designed to keep our community welcoming, safe, and focused on what brought us here: gaming.</p>

		<h2>Community Conduct</h2>
		<p>All members are entitled to respect. Gamers' Plane welcomes diverse viewpoints on gaming, and that will by definition include disagreement. However, we explicitly stand against hate and discrimination. This community is and will remain a safe and welcoming space for minorities and marginalized groups. Any discussion or debate should remain respectful and focused on the topic rather than on the individuals involved. Harassment, hate speech, and personal attacks are not permitted. This includes, but is not limited to: name-calling, belittling, bullying, or the use of slurs or derogatory language based on race, ethnicity, national origin, religion, disability, gender, gender identity, sexual orientation, or age.</p>

		<h2>Content Standards</h2>
		<p>Gamers' Plane is a site dedicated to gaming and the community around the games. With that in mind, discussions should primarily relate to gaming. Please avoid introducing divisive off-topic subjects such as politics, religion, or other current events not directly related to gaming. In particular, please note the following when posting in the public forums or on Discord:</p>
		<ol>
			<li><strong>Spam:</strong> Threads and posts should have clear content and purpose, whether introducing yourself or starting a discussion on a topic. Avoid spammy posts. Limit images to three per post and ensure they are relevant to the discussion.</li>
			<li><strong>Explicit Material & Profanity:</strong> We strive to maintain an environment appropriate for a general audience. Do not post pornography, sexually explicit content, or realistic depictions of gratuitous violence. Also, please refrain from excessive profanity. If it would get you an adult rating in a theater, it’s too much for Gamers' Plane.</li>
			<li><strong>Legally Prohibited Content:</strong> You may not post or share anything that is libelous, defamatory, or threatening, or that violates copyright or other intellectual property rights. This includes sharing or linking to copyrighted material without permission from the rights holder.</li>
			<li><strong>Site Security:</strong> You may not take any action intended to harm Gamers' Plane, its servers, or its content, nor may you attempt to circumvent its security measures. This includes, but is not limited to: posting on the site from two different accounts at the same time in secret. You may switch to a new account, but any disciplinary actions that applied to your old account will apply to your new account. Creating accounts to circumvent disciplinary actions or engage in inauthentic behaviour will result in an immediate ban.</li>
			<li><strong>Advertising:</strong> Promotion of commercial products or services is permitted only in the designated subforum or discord channel. You must be an existing member of the community in order to make posts advertising any product. All advertising must follow all other rules. Advertisements that follow a known pattern of scammers may be removed.</li>
			<li><strong>Off-Site Promotion:</strong> You may not use Gamers' Plane to advertise or promote other play-by-post sites, nor may you advertise games that take place elsewhere. You are welcome to use third-party tools to assist with games on Gamers' Plane, but the game itself should take place here.</li>
			<li><strong>Non-English Posts:</strong> Posts in public forums should be in English unless the thread is tagged for another language (e.g. [French], [German]) as the mods do not all speak other languages. If you do not include an English translation with your post, computer-based translation will be considered authoritative in the event of moderation.</li>
			<li><strong>Channel Purpose & Etiquette:</strong> Any thread or channel that is named for a specific purpose should be used only for that purpose. In the forums, for instance, game discussions belong in the appropriate Game Discussions forum, site ideas or problems belong under Site Discussions, and game requests belong under Games Tavern. In Discord, there are multiple channels for discussions of various systems. When possible, move a prolonged chat to the channel designated for the subject of that chat.</li>
			<li><strong>Spoilers:</strong> Everyone should have the chance to experience new movies, books, games, and other media. At the same time, those who have already done so may wish to discuss them. To balance these interests, we ask that you follow these guidelines: Any thread about a recent release (less than six months) that includes information not easily available to the public should be marked with [Spoilers] at the beginning of the thread title. In Discord, please use the built-in spoiler tags. If the thread merely mentions a release or discusses what is easy to find, the tag is not necessary. When in doubt, add the tag. After six months, tags are generally not required. However, some media releases content periodically (such as games with monthly updates), so please remain mindful of others who may not be current. Again, when in doubt, add the tag.</li>
		</ol>
		<p>Private game forums may permit looser language standards, provided this is clearly stated at the root forum or in the game details. Even in these spaces, users must abide by all other rules. Games may be run in other languages but should be tagged as noted in the previous section.</p>

		<h2>Moderation &amp; Enforcement</h2>
		<p>Gamers' Plane reserves the right to moderate content and enforce these rules at its sole discretion. Violations may result in content removal, warnings, temporary suspension, or permanent bans, depending on the nature and severity of the offense.</p>
		<p>If you have concerns over a moderation decision, you may appeal it to any moderator, keeping the discussion respectful and calm. Any issues with a moderator may be raised to the site owner, Keleth.</p>
		<p>We appreciate your cooperation in keeping Gamers' Plane a great place to game.</p>
<? require_once(FILEROOT.'/footer.php'); ?>
