services:
    proxy:
        build:
            context: ./docker/apache
            dockerfile: Dockerfile
        container_name: gpv1-proxy
        ports:
            - "127.0.0.1:80:80"
        volumes:
            - .:/var/www
            - ./docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
            - ./docker/apache/extra:/usr/local/apache2/conf/extra
            - ./docker/apache/vhosts/vhosts.${ENVIRONMENT}.conf:/usr/local/apache2/conf/vhosts.conf
            - ./logs/proxy:/var/log/
        depends_on:
            - api
        extra_hosts:
            - host.docker.internal:host-gateway

    api:
        build:
            context: ./
            dockerfile: docker/Dockerfile-php
        container_name: gpv1-api
        volumes:
            - ./:/var/www
            - ./logs/api:/dev/log
