SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


CREATE TABLE IF NOT EXISTS `dispatch` (
  `url` varchar(100) NOT NULL,
  `pageID` varchar(50) DEFAULT NULL,
  `file` varchar(100) NOT NULL,
  `title` varchar(50) DEFAULT NULL,
  `fixedGameMenu` tinyint(4) NOT NULL,
  `bodyClass` varchar(50) DEFAULT NULL,
  `active` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`url`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `dispatch` (`url`, `pageID`, `file`, `title`, `fixedGameMenu`, `bodyClass`, `active`) VALUES
('/', 'home', 'index.php', NULL, 0, NULL, 1),
('403/', '403', 'errors/403.php', 'Forbidden', 0, NULL, 1),
('404/', '404', 'errors/404.php', 'Not Found', 0, NULL, 1),
('characters/', 'myCharacters', 'characters/my.php', 'My Characters', 1, NULL, 1),
('characters/afmbe/(###)/', 'characterSheet_afmbe_sheet', 'characters/afmbe/sheet.php', 'All Flesh Must Be Eaten Character Sheet', 1, 'characterSheet viewCharacter', 1),
('characters/afmbe/(###)/edit/', 'characterSheet_afmbe_edit', 'characters/afmbe/edit.php', 'Edit All Flesh Must Be Eaten Character Sheet', 1, 'characterSheet editCharacter', 1),
('characters/ajax/dnd3/addFeat/', NULL, 'characters/ajax/dnd3/addFeat.php', NULL, 0, NULL, 1),
('characters/ajax/dnd3/addSkill/', NULL, 'characters/ajax/dnd3/addSkill.php', NULL, 0, NULL, 1),
('characters/ajax/dnd3/armor/', NULL, 'characters/ajax/dnd3/armor.php', NULL, 0, NULL, 1),
('characters/ajax/dnd3/removeFeat/', NULL, 'characters/ajax/dnd3/removeFeat.php', NULL, 0, NULL, 1),
('characters/ajax/dnd3/removeSkill/', NULL, 'characters/ajax/dnd3/removeSkill.php', NULL, 0, NULL, 1),
('characters/ajax/dnd3/weapon/', NULL, 'characters/ajax/dnd3/weapon.php', NULL, 0, NULL, 1),
('characters/ajax/dnd4/addAttack/', NULL, 'characters/ajax/dnd4/addAttack.php', NULL, 0, NULL, 1),
('characters/ajax/dnd4/addFeat/', NULL, 'characters/ajax/dnd4/addFeat.php', NULL, 0, NULL, 1),
('characters/ajax/dnd4/addPower/', NULL, 'characters/ajax/dnd4/addPower.php', NULL, 0, NULL, 1),
('characters/ajax/dnd4/addSkill/', NULL, 'characters/ajax/dnd4/addSkill.php', NULL, 0, NULL, 1),
('characters/ajax/dnd4/armor/', NULL, 'characters/ajax/dnd4/armor.php', NULL, 0, NULL, 1),
('characters/ajax/dnd4/powerSearch/', NULL, 'characters/ajax/dnd4/powerSearch.php', NULL, 0, NULL, 1),
('characters/ajax/dnd4/removeFeat/', NULL, 'characters/ajax/dnd4/removeFeat.php', NULL, 0, NULL, 1),
('characters/ajax/dnd4/removePower/', NULL, 'characters/ajax/dnd4/removePower.php', NULL, 0, NULL, 1),
('characters/ajax/dnd4/removeSkill/', NULL, 'characters/ajax/dnd4/removeSkill.php', NULL, 0, NULL, 1),
('characters/ajax/dnd4/weapon/', NULL, 'characters/ajax/dnd4/weapon.php', NULL, 0, NULL, 1),
('characters/ajax/featSearch/', NULL, 'characters/ajax/featSearch.php', NULL, 0, NULL, 1),
('characters/ajax/marvel/actionSearch/', NULL, 'characters/ajax/marvel/actionSearch.php', NULL, 0, NULL, 1),
('characters/ajax/marvel/addAction/', NULL, 'characters/ajax/marvel/addAction.php', NULL, 0, NULL, 1),
('characters/ajax/marvel/addChallenge/', NULL, 'characters/ajax/marvel/addChallenge.php', NULL, 0, NULL, 1),
('characters/ajax/marvel/addModifier/', NULL, 'characters/ajax/marvel/addModifier.php', NULL, 0, NULL, 1),
('characters/ajax/marvel/modifierSearch/', NULL, 'characters/ajax/marvel/modifierSearch.php', NULL, 0, NULL, 1),
('characters/ajax/pathfinder/addFeat/', NULL, 'characters/ajax/pathfinder/addFeat.php', NULL, 0, NULL, 1),
('characters/ajax/pathfinder/addSkill/', NULL, 'characters/ajax/pathfinder/addSkill.php', NULL, 0, NULL, 1),
('characters/ajax/pathfinder/armor/', NULL, 'characters/ajax/pathfinder/armor.php', NULL, 0, NULL, 1),
('characters/ajax/pathfinder/removeFeat/', NULL, 'characters/ajax/pathfinder/removeFeat.php', NULL, 0, NULL, 1),
('characters/ajax/pathfinder/removeSkill/', NULL, 'characters/ajax/pathfinder/removeSkill.php', NULL, 0, NULL, 1),
('characters/ajax/pathfinder/weapon/', NULL, 'characters/ajax/pathfinder/weapon.php', NULL, 0, NULL, 1),
('characters/ajax/skillSearch/', NULL, 'characters/ajax/skillSearch.php', NULL, 0, NULL, 1),
('characters/ajax/spycraft/addFeat/', NULL, 'characters/ajax/spycraft/addFeat.php', NULL, 0, NULL, 1),
('characters/ajax/spycraft/addSkill/', NULL, 'characters/ajax/spycraft/addSkill.php', NULL, 0, NULL, 1),
('characters/ajax/spycraft/armor/', NULL, 'characters/ajax/spycraft/armor.php', NULL, 0, NULL, 1),
('characters/ajax/spycraft/removeFeat/', NULL, 'characters/ajax/spycraft/removeFeat.php', NULL, 0, NULL, 1),
('characters/ajax/spycraft/removeSkill/', NULL, 'characters/ajax/spycraft/removeSkill.php', NULL, 0, NULL, 1),
('characters/ajax/spycraft/weapon/', NULL, 'characters/ajax/spycraft/weapon.php', NULL, 0, NULL, 1),
('characters/ajax/spycraft2/addFeat/', NULL, 'characters/ajax/spycraft2/addFeat.php', NULL, 0, NULL, 1),
('characters/ajax/spycraft2/addFocus/', NULL, 'characters/ajax/spycraft2/addFocus.php', NULL, 0, NULL, 1),
('characters/ajax/spycraft2/addSkill/', NULL, 'characters/ajax/spycraft2/addSkill.php', NULL, 0, NULL, 1),
('characters/ajax/spycraft2/armor/', NULL, 'characters/ajax/spycraft2/armor.php', NULL, 0, NULL, 1),
('characters/ajax/spycraft2/focusSearch/', NULL, 'characters/ajax/spycraft2/focusSearch.php', NULL, 0, NULL, 1),
('characters/ajax/spycraft2/removeFeat/', NULL, 'characters/ajax/spycraft2/removeFeat.php', NULL, 0, NULL, 1),
('characters/ajax/spycraft2/removeFocus/', NULL, 'characters/ajax/spycraft2/removeFocus.php', NULL, 0, NULL, 1),
('characters/ajax/spycraft2/removeSkill/', NULL, 'characters/ajax/spycraft2/removeSkill.php', NULL, 0, NULL, 1),
('characters/ajax/spycraft2/weapon/', NULL, 'characters/ajax/spycraft2/weapon.php', NULL, 0, NULL, 1),
('characters/cthulhu/(###)/', 'characterSheet_cthulhu_sheet', 'characters/cthulhu/sheet.php', 'Call of Cthulhu Character Sheet', 1, NULL, 1),
('characters/cthulhu/(###)/edit/', 'characterSheet_cthulhu_edit', 'characters/cthulhu/edit.php', 'Edit Call of Cthulhu Character Sheet', 1, NULL, 1),
('characters/cthulhu/new/', 'characterSheet_cthulhu_edit', 'characters/cthulhu/edit.php', 'Edit Call of Cthulhu Character Sheet', 1, NULL, 1),
('characters/custom/(###)/', 'characterSheet_custom_sheet', 'characters/custom/sheet.php', 'Custom Character Sheet', 1, 'characterSheet viewCharacter', 1),
('characters/custom/(###)/edit/', 'characterSheet_custom_edit', 'characters/custom/edit.php', 'Edit Custom Character Sheet', 1, 'characterSheet editCharacter', 1),
('characters/custom/new/', 'characterSheet_custom_edit', 'characters/custom/edit.php', 'Edit Custom Character Sheet', 1, NULL, 1),
('characters/deadlands/(###)/', 'characterSheet_deadlands_sheet', 'characters/deadlands/sheet.php', 'Deadlands Character Sheet', 1, 'characterSheet viewCharacter', 1),
('characters/deadlands/(###)/edit/', 'characterSheet_deadlands_edit', 'characters/deadlands/edit.php', 'Edit Deadlands Character Sheet', 1, 'characterSheet editCharacter', 1),
('characters/delete/', 'deleteCharacter', 'characters/delete.php', 'Delete Character', 0, NULL, 1),
('characters/dnd3/(###)/', 'characterSheet_dnd3_sheet', 'characters/dnd3/sheet.php', 'Dungeons &amp; Dragons 3/3.5 Character Sheet', 1, 'characterSheet viewCharacter', 1),
('characters/dnd3/(###)/edit/', 'characterSheet_dnd3_edit', 'characters/dnd3/edit.php', 'Edit Dungeons &amp; Dragons 3/3.5 Character Sheet', 1, 'characterSheet editCharacter', 1),
('characters/dnd3/(###)/editFeatNotes/', 'characterSheet_dnd3_editFeatNotes', 'characters/dnd3/editFeatNotes.php', 'Dungeons &amp; Dragons 3/3.5 Edit Feat Notes', 0, NULL, 1),
('characters/dnd3/(###)/featNotes/', 'characterSheet_dnd3_featNotes', 'characters/dnd3/featNotes.php', 'Dungeons &amp; Dragons 3/3.5 Feat Notes', 0, NULL, 1),
('characters/dnd4/(###)/', 'characterSheet_dnd4_sheet', 'characters/dnd4/sheet.php', 'Dungeons &amp; Dragons 4th Character Sheet', 1, 'characterSheet viewCharacter', 1),
('characters/dnd4/(###)/edit/', 'characterSheet_dnd4_edit', 'characters/dnd4/edit.php', 'Edit Dungeons &amp; Dragons 4th Character Sheet', 1, 'characterSheet editCharacter', 1),
('characters/dnd4/(###)/editFeatNotes/', 'characterSheet_dnd4_editFeatNotes', 'characters/dnd4/editFeatNotes.php', 'Dungeons &amp; Dragons 4th Edit Feat Notes', 1, NULL, 1),
('characters/dnd4/(###)/featNotes/', 'characterSheet_dnd4_featNotes', 'characters/dnd4/featNotes.php', 'Dungeons &amp; Dragons 4th Feat Notes', 0, NULL, 1),
('characters/dnd4/new/', 'characterSheet_dnd4_edit', 'characters/dnd4/edit.php', 'Edit Dungeons &amp; Dragons 4th Character Sheet', 1, NULL, 1),
('characters/editLabel/', 'editLabel', 'characters/editLabel.php', 'Edit Label', 0, NULL, 1),
('characters/gurps/(###)/', 'characterSheet_gurps_sheet', 'characters/gurps/sheet.php', 'GURPS Character Sheet', 1, 'characterSheet viewCharacter', 1),
('characters/gurps/(###)/edit/', 'characterSheet_gurps_edit', 'characters/gurps/edit.php', 'Edit GURPS Character Sheet', 1, 'characterSheet editCharacter', 1),
('characters/gurps/new/', 'characterSheet_gurps_edit', 'characters/gurps/edit.php', 'Edit GURPS Character Sheet', 1, NULL, 1),
('characters/marvel/(###)/', 'characterSheet_marvel_sheet', 'characters/marvel/sheet.php', 'Marvel Character Sheet', 1, 'characterSheet viewCharacter', 1),
('characters/marvel/(###)/edit/', 'characterSheet_marvel_edit', 'characters/marvel/edit.php', 'Edit Marvel Character Sheet', 1, 'characterSheet editCharacter', 1),
('characters/marvel/new/', 'characterSheet_marvel_edit', 'characters/marvel/edit.php', 'Edit Marvel Character Sheet', 1, NULL, 1),
('characters/new/', 'newCharacter', 'characters/new.php', 'New Character', 0, NULL, 1),
('characters/pathfinder/(###)/', 'characterSheet_pathfinder_sheet', 'characters/pathfinder/sheet.php', 'Pathfinder Character Sheet', 1, 'characterSheet viewCharacter', 1),
('characters/pathfinder/(###)/edit/', 'characterSheet_pathfinder_edit', 'characters/pathfinder/edit.php', 'Edit Pathfinder Character Sheet', 1, 'characterSheet editCharacter', 1),
('characters/pathfinder/(###)/editFeatNotes/', 'characterSheet_pathfinder_editFeatNotes', 'characters/pathfinder/editFeatNotes.php', 'Pathfinder Edit Feat Notes', 1, NULL, 1),
('characters/pathfinder/(###)/featNotes/', 'characterSheet_pathfinder_featNotes', 'characters/pathfinder/featNotes.php', 'Pathfinder Feat Notes', 0, NULL, 1),
('characters/pathfinder/new/', 'characterSheet_pathfinder_edit', 'characters/pathfinder/edit.php', 'Edit Pathfinder Character Sheet', 1, NULL, 1),
('characters/process/afmbe/', NULL, 'characters/process/afmbe/edit.php', NULL, 0, NULL, 1),
('characters/process/cthulhu/', NULL, 'characters/process/cthulhu/edit.php', NULL, 0, NULL, 1),
('characters/process/custom/', NULL, 'characters/process/custom/edit.php', NULL, 0, NULL, 1),
('characters/process/deadlands/', NULL, 'characters/process/deadlands/edit.php', NULL, 0, NULL, 1),
('characters/process/delete/', NULL, 'characters/process/delete.php', NULL, 0, NULL, 1),
('characters/process/dnd3/', NULL, 'characters/process/dnd3/edit.php', NULL, 0, NULL, 1),
('characters/process/dnd3/editFeatNotes/', NULL, 'characters/process/dnd3/editFeatNotes.php', NULL, 0, NULL, 1),
('characters/process/dnd4/', NULL, 'characters/process/dnd4/edit.php', NULL, 0, NULL, 1),
('characters/process/dnd4/editFeatNotes/', NULL, 'characters/process/dnd4/editFeatNotes.php', NULL, 0, NULL, 1),
('characters/process/editLabel/', NULL, 'characters/process/editLabel.php', NULL, 0, NULL, 1),
('characters/process/gurps/', NULL, 'characters/process/gurps/edit.php', NULL, 0, NULL, 1),
('characters/process/marvel/', NULL, 'characters/process/marvel/edit.php', NULL, 0, NULL, 1),
('characters/process/new/', NULL, 'characters/process/new.php', NULL, 0, NULL, 1),
('characters/process/pathfinder/', NULL, 'characters/process/pathfinder/edit.php', NULL, 0, NULL, 1),
('characters/process/pathfinder/editFeatNotes/', NULL, 'characters/process/pathfinder/editFeatNotes.php', NULL, 0, NULL, 1),
('characters/process/shadowrun4/', NULL, 'characters/process/shadowrun4/edit.php', NULL, 0, NULL, 1),
('characters/process/spycraft/', NULL, 'characters/process/spycraft/edit.php', NULL, 0, NULL, 1),
('characters/process/spycraft/editFeatNotes/', NULL, 'characters/process/spycraft/editFeatNotes.php', NULL, 0, NULL, 1),
('characters/process/spycraft2/', NULL, 'characters/process/spycraft2/edit.php', NULL, 0, NULL, 1),
('characters/process/spycraft2/editFeatNotes/', NULL, 'characters/process/spycraft2/editFeatNotes.php', NULL, 0, NULL, 1),
('characters/process/wod/', NULL, 'characters/process/wod/edit.php', NULL, 0, NULL, 1),
('characters/shadowrun4/(###)/', 'characterSheet_shadowrun4_sheet', 'characters/shadowrun4/sheet.php', 'Shadowrun (4th) Character Sheet', 1, 'characterSheet viewCharacter', 1),
('characters/shadowrun4/(###)/edit/', 'characterSheet_shadowrun4_edit', 'characters/shadowrun4/edit.php', 'Edit Shadowrun (4th) Character Sheet', 1, 'characterSheet editCharacter', 1),
('characters/shadowrun4/new/', 'characterSheet_shadowrun4_edit', 'characters/shadowrun4/edit.php', 'Edit Shadowrun (4th) Character Sheet', 1, NULL, 1),
('characters/spycraft/(###)/', 'characterSheet_spycraft_sheet', 'characters/spycraft/sheet.php', 'Spycraft (1st Edition) Character Sheet', 1, 'characterSheet viewCharacter', 1),
('characters/spycraft/(###)/edit/', 'characterSheet_spycraft_edit', 'characters/spycraft/edit.php', 'Edit Spycraft (1st Edition) Character Sheet', 1, 'characterSheet editCharacter', 1),
('characters/spycraft/(###)/editFeatNotes/', 'characterSheet_spycraft_editFeatNotes', 'characters/spycraft/editFeatNotes.php', 'Spycraft (1st Edition) Edit Feat Notes', 1, NULL, 1),
('characters/spycraft/(###)/featNotes/', 'characterSheet_spycraft_featNotes', 'characters/spycraft/featNotes.php', 'Spycraft (1st Edition) Feat Notes', 0, NULL, 1),
('characters/spycraft/new/', 'characterSheet_spycraft_edit', 'characters/spycraft/edit.php', 'Edit Spycraft (1st Edition) Character Sheet', 1, NULL, 1),
('characters/spycraft2/(###)/', 'characterSheet_spycraft2_sheet', 'characters/spycraft2/sheet.php', 'Spycraft 2.0 Character Sheet', 1, 'characterSheet viewCharacter', 1),
('characters/spycraft2/(###)/edit/', 'characterSheet_spycraft2_edit', 'characters/spycraft2/edit.php', 'Edit Spycraft 2.0 Character Sheet', 1, 'characterSheet editCharacter', 1),
('characters/spycraft2/(###)/editFeatNotes/', 'characterSheet_spycraft2_editFeatNotes', 'characters/spycraft2/editFeatNotes.php', 'Spycraft 2.0 Edit Feat Notes', 1, NULL, 1),
('characters/spycraft2/(###)/featNotes/', 'characterSheet_spycraft2_featNotes', 'characters/spycraft2/featNotes.php', 'Spycraft 2.0 Feat Notes', 0, NULL, 1),
('characters/spycraft2/new/', 'characterSheet_spycraft2_edit', 'characters/spycraft2/edit.php', 'Edit Spycraft 2.0 Character Sheet', 1, NULL, 1),
('characters/wod/(###)/', 'characterSheet_wod_sheet', 'characters/wod/sheet.php', 'World of Darkness Character Sheet', 1, 'characterSheet viewCharacter', 1),
('characters/wod/(###)/edit/', 'characterSheet_wod_edit', 'characters/wod/edit.php', 'Edit World of Darkness Character Sheet', 1, 'characterSheet editCharacter', 1),
('characters/wod/new/', 'characterSheet_wod_edit', 'characters/wod/edit.php', 'Edit World of Darkness Character Sheet', 1, NULL, 1),
('contact/', 'contact', 'contact/contact.php', 'Contact Us', 0, NULL, 1),
('contact/process/', NULL, 'contact/process/contact.php', NULL, 0, NULL, 1),
('contact/success/', 'contact_success', 'contact/success.php', 'Contact Us', 0, NULL, 1),
('forums/', 'forum', 'forums/forum.php', 'Forums', 0, NULL, 1),
('forums/acp/', 'forumACP', 'forums/acp/acp.php', 'ACP', 0, NULL, 1),
('forums/acp/permissions/', 'forumACP_permissions', 'forums/acp/permissions.php', 'ACP - Permissions', 0, NULL, 1),
('forums/delete/', 'forum_delete', 'forums/delete.php', 'Delete', 0, NULL, 1),
('forums/editPost/', 'forum_post', 'forums/post.php', 'Edit Post', 0, NULL, 1),
('forums/moveThread/', 'forum_moveThread', 'forums/moveThread.php', 'Move Thread', 0, NULL, 1),
('forums/newThread/', 'forum_post', 'forums/post.php', 'New Thread', 0, NULL, 1),
('forums/post/', 'forum_post', 'forums/post.php', 'Post', 0, NULL, 1),
('forums/process/acp/delete/', NULL, 'forums/acp/process/delete.php', NULL, 0, NULL, 1),
('forums/process/acp/edit/', NULL, 'forums/acp/process/edit.php', NULL, 0, NULL, 1),
('forums/process/acp/move/', NULL, 'forums/acp/process/move.php', NULL, 0, NULL, 1),
('forums/process/acp/new/', NULL, 'forums/acp/process/new.php', NULL, 0, NULL, 1),
('forums/process/acp/permissions/', NULL, 'forums/acp/process/permissions.php', NULL, 0, NULL, 1),
('forums/process/cardVis/', NULL, 'forums/process/cardVis.php', NULL, 0, NULL, 1),
('forums/process/delete/', NULL, 'forums/process/delete.php', NULL, 0, NULL, 1),
('forums/process/modThread/', NULL, 'forums/process/modThread.php', NULL, 0, NULL, 1),
('forums/process/moveThread/', NULL, 'forums/process/moveThread.php', NULL, 0, NULL, 1),
('forums/process/post/', NULL, 'forums/process/post.php', NULL, 0, NULL, 1),
('forums/process/read/', NULL, 'forums/process/read.php', NULL, 0, NULL, 1),
('forums/process/vote/', NULL, 'forums/process/vote.php', NULL, 0, NULL, 1),
('forums/rules/', 'forum_rules', 'forums/rules.php', 'Forum Rules', 0, NULL, 1),
('forums/search/', 'forum_search', 'forums/search.php', 'Search', 0, NULL, 1),
('forums/thread/', 'forum_thread', 'forums/thread.php', 'Thread', 0, NULL, 1),
('gamersList/', 'gamersList', 'ucp/list.php', 'Gamers List', 0, NULL, 1),
('games/', 'myGames', 'games/my.php', 'My Games', 0, NULL, 1),
('games/(###)/', 'gameDetails', 'games/details.php', NULL, 1, NULL, 1),
('games/(###)/approvePlayer/', 'game_pendingPlayer', 'games/pendingPlayer.php', 'Approve Player', 1, NULL, 1),
('games/(###)/decks/', 'gameDecks', 'games/decks.php', 'Game Decks', 1, NULL, 1),
('games/(###)/edit/', 'editGame', 'games/edit.php', 'Edit Game', 1, NULL, 1),
('games/(###)/leaveGame/', 'leaveGame', 'games/leaveGame.php', 'Leave Game', 1, NULL, 1),
('games/(###)/rejectPlayer/', 'game_pendingPlayer', 'games/pendingPlayer.php', 'Reject Player', 1, NULL, 1),
('games/(###)/removePlayer/', 'game_removePlayer', 'games/removePlayer.php', 'Remove Player', 1, NULL, 1),
('games/(###)/toggleGM/', 'toggleGM', 'games/toggleGM.php', '', 1, NULL, 1),
('games/ajax/gamesSearch/', NULL, 'games/ajax/gamesSearch.php', NULL, 0, NULL, 1),
('games/changeStatus/', 'changeGameStatus', 'games/changeStatus.php', 'Change Game Status', 0, NULL, 1),
('games/lfg/', 'lfg', 'games/lfg.php', 'Looking for Game', 0, NULL, 1),
('games/list/', 'listGames', 'games/list.php', 'All Games', 0, NULL, 1),
('games/new/', 'newGame', 'games/edit.php', 'New Game', 0, NULL, 1),
('games/process/changeStatus/', NULL, 'games/process/changeStatus.php', NULL, 0, NULL, 1),
('games/process/deck/', NULL, 'games/process/deck.php', NULL, 0, NULL, 1),
('games/process/edit/', NULL, 'games/process/gameDetails.php', NULL, 0, NULL, 1),
('games/process/join/', NULL, 'games/process/join.php', NULL, 0, NULL, 1),
('games/process/leave/', NULL, 'games/process/removePlayer.php', NULL, 0, NULL, 1),
('games/process/lfg/', NULL, 'games/process/lfg.php', NULL, 0, NULL, 1),
('games/process/new/', NULL, 'games/process/gameDetails.php', NULL, 0, NULL, 1),
('games/process/pendingPlayer/', NULL, 'games/process/pendingPlayer.php', NULL, 0, NULL, 1),
('games/process/removePlayer/', NULL, 'games/process/removeChar.php', NULL, 0, NULL, 1),
('games/process/toggleGM/', NULL, 'games/process/toggleGM.php', NULL, 0, NULL, 1),
('login/', 'login', 'login/login.php', 'Login', 0, NULL, 1),
('login/process/login/', NULL, 'login/process/login.php', NULL, 0, NULL, 1),
('login/process/requestReset/', NULL, 'login/process/requestReset.php', NULL, 0, NULL, 1),
('login/process/resetPass/', NULL, 'login/process/resetPass.php', NULL, 0, NULL, 1),
('login/requestReset/', 'requestReset', 'login/requestReset.php', 'Request Password Reset', 0, NULL, 1),
('login/resetPass/', 'resetPass', 'login/resetPass.php', 'Reset Password', 0, NULL, 1),
('logout/', NULL, 'login/process/logout.php', NULL, 0, NULL, 1),
('pms/', 'pms', 'pms/list.php', 'Private Messages', 0, NULL, 1),
('pms/ajax/userSearch/', NULL, 'pms/ajax/userSearch.php', NULL, 0, NULL, 1),
('pms/delete/', 'pm_delete', 'pms/delete.php', 'Delete Private Message', 0, NULL, 1),
('pms/process/delete/', NULL, 'pms/process/delete.php', NULL, 0, NULL, 1),
('pms/process/reply/', NULL, 'pms/process/send.php', NULL, 0, NULL, 1),
('pms/process/send/', NULL, 'pms/process/send.php', NULL, 0, NULL, 1),
('pms/reply/', 'pm_send', 'pms/send.php', 'Reply', 0, NULL, 1),
('pms/send/', 'pm_send', 'pms/send.php', 'Send Private Message', 0, NULL, 1),
('pms/success/sent/', 'pms_success_sent', 'pms/success/send.php', 'Success', 0, NULL, 1),
('pms/view/', 'pm_view', 'pms/view.php', 'Private Message', 0, NULL, 1),
('register/', 'register', 'register/register.php', 'Register', 0, NULL, 1),
('register/activate/', 'regActivate', 'register/activate.php', 'Activate Registration', 0, NULL, 1),
('register/ajax/loginSearch/', NULL, 'register/ajax/loginSearch.php', NULL, 0, NULL, 1),
('register/process/register/', NULL, 'register/process/register.php', NULL, 0, NULL, 1),
('register/success/', 'regSuccess', 'register/success.php', 'Registration Success', 0, NULL, 1),
('tools/', 'tools', 'tools/tools.php', 'Tools', 0, NULL, 1),
('tools/ajax/chat/retrieveMessages.php/', NULL, 'tools/ajax/chat/retrieveMessages.php', NULL, 0, NULL, 1),
('tools/ajax/chat/retrieveUsers.php/', NULL, 'tools/ajax/chat/retrieveUsers.php', NULL, 0, NULL, 1),
('tools/ajax/chat/sendMessage/', NULL, 'tools/ajax/chat/sendMessage.php', NULL, 0, NULL, 1),
('tools/ajax/decks/', NULL, 'tools/ajax/decks.php', NULL, 0, NULL, 1),
('tools/ajax/dice/', NULL, 'tools/ajax/dice.php', NULL, 0, NULL, 1),
('tools/ajax/maps/iconData/', NULL, 'tools/ajax/maps/iconData.php', NULL, 0, NULL, 1),
('tools/ajax/maps/save/', NULL, 'tools/ajax/maps/save.php', NULL, 0, NULL, 1),
('tools/ajax/maps/updateLoc/', NULL, 'tools/ajax/maps/updateLoc.php', NULL, 0, NULL, 1),
('tools/ajax/newDeck/', NULL, 'tools/ajax/newDeck.php', NULL, 0, NULL, 1),
('tools/cards/', 'tools_cards', 'tools/cards.php', 'Cards', 0, NULL, 1),
('tools/chat/', 'chat', 'tools/chat/chat.php', 'Chat', 1, NULL, 1),
('tools/chat/cron/logChat/', NULL, 'tools/chat/cron/logChat.php', NULL, 0, NULL, 1),
('tools/dice/', 'tools_dice', 'tools/dice.php', 'Dice', 0, NULL, 1),
('tools/maps/', 'mapList', 'tools/maps/list.php', 'Maps', 1, NULL, 1),
('tools/maps/edit/', 'editMap', 'tools/maps/edit.php', 'Edit Map', 1, NULL, 1),
('tools/maps/iconHistory/', 'iconHistory', 'tools/maps/iconHistory.php', 'Icon History', 1, NULL, 1),
('tools/maps/mapDetails/', 'mapDetails', 'tools/maps/mapDetails.php', 'Map Details', 1, NULL, 1),
('tools/maps/new/', 'newMap', 'tools/maps/new.php', 'New Map', 1, NULL, 1),
('tools/maps/view/', 'map', 'tools/maps/map.php', NULL, 1, NULL, 1),
('tools/process/cards/', NULL, 'tools/process/cards.php', NULL, 0, NULL, 1),
('tools/process/maps/addCR/', NULL, 'tools/process/maps/addCR.php', NULL, 0, NULL, 1),
('tools/process/maps/icons/', NULL, 'tools/process/maps/icons.php', NULL, 0, NULL, 1),
('tools/process/maps/new/', NULL, 'tools/process/maps/new.php', NULL, 0, NULL, 1),
('tools/process/maps/removeCR/', NULL, 'tools/process/maps/removeCR.php', NULL, 0, NULL, 1),
('tools/process/maps/saveDetails/', NULL, 'tools/process/maps/saveDetails.php', NULL, 0, NULL, 1),
('ucp/', 'ucp', 'ucp/ucp.php', 'User Control Panel', 0, NULL, 1),
('ucp/process/changeDetails/', NULL, 'ucp/process/changeDetails.php', NULL, 0, NULL, 1),
('ucp/process/changeForumOptions/', NULL, 'ucp/process/changeForumOptions.php', NULL, 0, NULL, 1),
('ucp/process/changeInfo/', NULL, 'ucp/process/changeInfo.php', NULL, 0, NULL, 1),
('unauthorized/', '401', 'errors/401.php', 'Unauthorized', 0, NULL, 1),
('user/', 'user', 'ucp/user.php', 'User', 0, NULL, 1);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
