FROM php:7.3-fpm

RUN apt-get update
RUN apt-get install -y \
	autoconf \
	file \
	g++ \
	gcc \
	zlib1g-dev \
	libpng-dev \
	make \
	libmemcached-dev \
	# libjpeg-turbo8-dev \
	&& pecl install memcached \
	&& docker-php-ext-enable memcached
RUN pecl install xdebug-2.7.0RC2 \
	&& docker-php-ext-enable xdebug
RUN pecl install mongodb \
	&& docker-php-ext-enable mongodb
RUN docker-php-ext-install pdo_mysql
# RUN docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr \
# 	&& docker-php-ext-install gd
RUN docker-php-ext-install gd

# RUN DEBIAN_FRONTEND=noninteractive apt-get -y install postfix
# COPY docker/php/conf.ini .
# RUN mv ./conf.ini $PHP_INI_DIR/conf.d/conf.ini
# COPY docker/postfix/main.cf .
# RUN mv ./main.cf /etc/postfix/main.cf

# RUN mv $PHP_INI_DIR/php.ini-production $PHP_INI_DIR/php.ini

WORKDIR /var/www
