FROM php:7.3-fpm-alpine

RUN apk update
RUN apk add \
	autoconf \
	file \
	g++ \
	gcc \
	zlib-dev \
	libpng-dev \
	make \
	libmemcached-dev \
	gd \
	&& pecl install memcached \
	&& docker-php-ext-enable memcached
RUN pecl install xdebug-2.7.0RC2 \
	&& docker-php-ext-enable xdebug
RUN pecl install mongodb \
	&& docker-php-ext-enable mongodb
RUN docker-php-ext-install pdo_mysql
RUN docker-php-ext-install gd
WORKDIR /var/www