version: '3.6'

services:
  proxy:
    volumes:
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./apache/extra:/usr/local/apache2/conf/extra

  mysql:
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=test123
      - MYSQL_DATABASE=gamersplanev1
      - MYSQL_USER=gamersplane
      - MYSQL_PASSWORD=test123
