FROM php:7.3-fpm

RUN apt-get update
RUN apt-get install -y \
	autoconf \
	file \
	g++ \
	gcc \
	zlib1g-dev \
	make \
	libmemcached-dev \
	ca-certificates \
	libjpeg62-turbo-dev \
	libpng-dev \
	&& pecl install memcached \
	&& docker-php-ext-enable memcached
RUN sed -i -r 's/^(.*CN-?EXT)/##\1/' /usr/lib/x86_64-linux-gnu/gconv/gconv-modules \
	&& iconvconfig /usr/lib/x86_64-linux-gnu/gconv/ \
	&& iconv -l | grep -E 'CN-?EXT' && exit 1 || true
RUN pecl install xdebug-2.7.0RC2 \
	&& docker-php-ext-enable xdebug
RUN pecl install mongodb-1.16.2 \
	&& docker-php-ext-enable mongodb
RUN docker-php-ext-install pdo_mysql
RUN docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr \
	&& docker-php-ext-install gd

COPY docker/php/php.ini "$PHP_INI_DIR/php.ini"
# RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

WORKDIR /var/www
