version: '3.6'

services:
  proxy:
    container_name: gamersplane-proxy
    ports:
      - 80:80
    volumes:
      - ../:/var/www

  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=p2HR1IQGF8c!A&amp;f&amp;
      - MYSQL_PASSWORD=&amp;R6ivIqTS0b#wQ7e
